services:

  discovery:
    build: ./Discovery
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  backend1:
    build: ./Back-end
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DISCOVERY_URL=http://discovery:4000

  middleware:
    build: ./Middleware
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BACKEND_URL_1=http://backend1:3004
      - DISCOVERY_URL=http://discovery:4000

  frontend:
    build: ./Front-end
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
