version: '3'
services:
  backend1:
    build: ./backend
    ports:
      - "3004:3004"
    environment:
      - PORT=3004

  backend2:
    build: ./backend
    ports:
      - "3005:3005"
    environment:
      - PORT=3005

  middleware:
    build: ./middleware
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BACKEND_URL_1=http://backend1:3004
      - BACKEND_URL_2=http://backend2:3005

  frontend:
    build: ./frontend
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
