version: '3'
services:
  backend1:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  backend2:
    build: ./backend
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  middleware:
    build: ./middleware
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BACKEND_URL_1=http://backend1:3000
      - BACKEND_URL_2=http://backend2:3002
