services:

  discovery:
    build: ./Discovery
    ports:
      - "4000:4000"
    environment:
      - DISCOVERY_PORT=4000
    networks:
      - app-network



  backend1:
    build: ./Back-end
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - DISCOVERY_URL=http://discovery:4000
    networks:
      - app-network
  backend2:
    build: ./Back-end
    ports:
      - "3005:3005"
    environment:
      - PORT=3004
      - DISCOVERY_URL=http://discovery:4000
    networks:
      - app-network

  middleware:
    build: ./Middleware
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DISCOVERY_URL=http://discovery:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge